### ISSUE TITLE
게임 뒤로가기 버그

### ISSUE THREAD

**Issue by contemplation-person** [pong-nyan/pong-nyan#260]
뒤로가기를 막아놔야 할 것 같음.
<img width="402" alt="Screen Shot 2023-09-16 at 4 21 38 PM" src="https://github.com/pong-nyan/pong-nyan/assets/68673565/1568f828-7678-440f-a8cf-00c938284f63">

**Comment by YeonSeong-Lee** [comment]
프론트에서 5점 이상이면 그냥 메임으로 가버리기
